# Generated by Django 6.0.3 on 2026-03-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemreview',
            name='author',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='სურათი'),
        ),
        migrations.AddField(
            model_name='item',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='გამოშვების თარიღი'),
        ),
        migrations.AddField(
            model_name='itemreview',
            name='reviewer_name',
            field=models.CharField(default='Anonymous', max_length=100, verbose_name='შემფასებლის სახელი და გვარი'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemreview',
            name='comment',
            field=models.TextField(verbose_name='კომენტარი'),
        ),
        migrations.AlterField(
            model_name='itemreview',
            name='rating_stars',
            field=models.IntegerField(default=5, verbose_name='რეიტინგი (1-5)'),
        ),
    ]
