# Generated by Django 6.0.3 on 2026-03-10 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='დასახელება')),
                ('brand', models.CharField(max_length=100, verbose_name='ბრენდი')),
                ('category', models.CharField(max_length=100, verbose_name='კატეგორია')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ფასი')),
                ('description', models.TextField(verbose_name='აღწერა')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='რაოდენობა საწყობში')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='სურათი')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='გამოშვების თარიღი')),
            ],
        ),
        migrations.CreateModel(
            name='ItemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100, verbose_name='შემფასებლის სახელი და გვარი')),
                ('rating_stars', models.IntegerField(default=5, verbose_name='რეიტინგი (1-5)')),
                ('comment', models.TextField(verbose_name='კომენტარი')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.item')),
            ],
        ),
    ]
