# Generated by Django 6.0.3 on 2026-03-10 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreview',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='itemreview',
            name='rating_stars',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='itemreview',
            name='reviewer_name',
            field=models.CharField(max_length=100, verbose_name='შემფასებლის სახელი'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
