# Generated by Django 6.0.3 on 2026-03-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_itemreview_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreview',
            name='comment',
            field=models.TextField(verbose_name='კომენტარი'),
        ),
        migrations.AlterField(
            model_name='itemreview',
            name='rating_stars',
            field=models.IntegerField(default=5, verbose_name='რეიტინგი (1-5)'),
        ),
        migrations.AlterField(
            model_name='itemreview',
            name='reviewer_name',
            field=models.CharField(max_length=100, verbose_name='შემფასებლის სახელი და გვარი'),
        ),
    ]
